name: auth
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.9.0 <4.0.0' # SDK versiyon aralığı belirtildi.

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Firebase ve kimlik doğrulama paketleri
  firebase_core: ^3.1.0
  firebase_auth: ^5.1.2
  sign_in_with_apple: ^6.1.0
  google_sign_in: ^6.2.1
  flutter_bloc: ^8.1.5

  # SVG desteği için
  flutter_svg: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # Asset tanımı
  assets:
    - lib/assets/
