// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNqE-uZVTs7SXdMhFn9dfenrbrrkY2CdE',
    appId: '1:434840764133:web:481885c1224289cc811e0c',
    messagingSenderId: '434840764133',
    projectId: 'authtutorial-d4b86',
    authDomain: 'authtutorial-d4b86.firebaseapp.com',
    storageBucket: 'authtutorial-d4b86.firebasestorage.app',
    measurementId: 'G-QJFTS4N9MG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAppkB1BPGX-u2Z8MqWqV4u8vmPRD8IG3Q',
    appId: '1:434840764133:android:9e2d257b8c1791cf811e0c',
    messagingSenderId: '434840764133',
    projectId: 'authtutorial-d4b86',
    storageBucket: 'authtutorial-d4b86.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhnOOtiYtKq-ihquTcPUo-USqsSenbOLQ',
    appId: '1:434840764133:ios:d11369cfb80a60ba811e0c',
    messagingSenderId: '434840764133',
    projectId: 'authtutorial-d4b86',
    storageBucket: 'authtutorial-d4b86.firebasestorage.app',
    iosBundleId: 'com.mustafaemirata.auth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhnOOtiYtKq-ihquTcPUo-USqsSenbOLQ',
    appId: '1:434840764133:ios:817e8d927163b57d811e0c',
    messagingSenderId: '434840764133',
    projectId: 'authtutorial-d4b86',
    storageBucket: 'authtutorial-d4b86.firebasestorage.app',
    iosBundleId: 'com.example.auth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBNqE-uZVTs7SXdMhFn9dfenrbrrkY2CdE',
    appId: '1:434840764133:web:25565a90181c36f4811e0c',
    messagingSenderId: '434840764133',
    projectId: 'authtutorial-d4b86',
    authDomain: 'authtutorial-d4b86.firebaseapp.com',
    storageBucket: 'authtutorial-d4b86.firebasestorage.app',
    measurementId: 'G-5DM0T2JZ55',
  );
}
